remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
- jekyll-feed

title: der frühling entertainment
description: der frühling's website for information and project updates

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
